### ISSUE TITLE
The calendar is not distinguishing between the month and the day when specified

### ISSUE THREAD

**Issue by 11bluetree** [toyamarinyon/coral#12]
※ translated by google🙏

## Overview
As the title suggests.

## Reproduction Steps

1. Change the calendar to 2023/08/11.
2. The daily report for 2023/11/08 appears.

## Expected Correct Behavior
Only the daily report for the specified date should be displayed.

## Possible Causes and Fixes
Unknown.

## Logs & Screenshots
![image](https://github.com/toyamarinyon/coral/assets/53058630/a2088fa9-ae68-4af8-a658-8afdca21365f)

I've recently started using it. It's very easy to view and has been very helpful ☺️
Nothing but gratitude.

**Comment by toyamarinyon** [comment]
Thanks you for the report 😄 
I'll check it.

**Comment by toyamarinyon** [comment]
fix it with https://github.com/toyamarinyon/coral/commit/2f80401b2883b20253fe5b7126af439076c2959b

**Comment by 11bluetree** [comment]
Thanks much !
