### ISSUE TITLE
【要望】labelで絞り込む機能があると嬉しい

### ISSUE THREAD

**Issue by kumanoayumi** [toyamarinyon/coral#4]
TBD
イメージを後で書きます

**Comment by toyamarinyon** [comment]
設定画面で追加のクエリを指定できるようにしてみました！
具体的な設定イメージは明日お知らせしますが、githubの検索で使えるものはand検索もor検索もできるはずです！
![image](https://github.com/toyamarinyon/coral/assets/535254/f492d2e7-1eda-4e82-8c33-0bb4947e9706)

ただ、これは一度設定したら気軽に変えられなくて、管理的にはいいのですが、ソフトウェアとしてはあまりいい設計ではないと思っています。（とはいえできたほうが便利なのでエスケープハッチ的追加しました。）
本当は手軽に切り替えて覗き見してみたり、フィードの途中にラベルの違う情報が出てきたりして偶発的な出会いが生まれる仕掛けを色々と入れたいです。

**Comment by kumanoayumi** [comment]
すごい…！ありがとうございます！🚀
早速活用させていただきます🙌

> 偶発的な出会いが生まれる仕掛けを色々と入れたい

素敵ですね、楽しみにしています🥳

**Comment by kumanoayumi** [comment]
挙動確認できたのでissue closeさせていただきます！
ありがとうございました！:pray:
